[package]
name = "grpc-status"
version = "0.1.0"
authors = ["nbari <nbari@tequila.io>"]
edition = "2018"

[dependencies]
clap = "2.33"
prost = "0.7"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.4"

[build-dependencies]
tonic-build = "0.4"
